# Generated by Django 4.0 on 2022-01-04 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='static/img/ava.jpg', upload_to='static/upload/', verbose_name='avatar'),
        ),
    ]
